# Generated by Django 4.1.7 on 2023-04-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_sepet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='urun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.urun'),
        ),
    ]
