# Generated by Django 4.1.7 on 2023-04-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0011_odeme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Odeme',
        ),
    ]
